config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  devise_for :admins

  get 'users/:id' => 'users#show'

  get 'users' => 'users#index'

  resources :home

  resources :boats

  resources :jobs, except: [:show, :index]

  resources :follows, only: [:create, :destroy]
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/boat.rb
class Boat < ActiveRecord::Base
	belongs_to :user
	has_many :jobs
	has_many :follows
	has_many :admirers, through: :follows, source: :user

	has_attached_file :boat_pic, :styles => { :medium => "500x500>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :boat_pic, :content_type => /\Aimage\/.*\Z/

	validates :name, uniqueness: true

	validates :location, inclusion: {in: ["Miami", "Chicago", "Portland", "New York City", "Balitmore", "Boston", "Shanghai", "London", "Amsterdam", "Sydney", "Capetown"]}
end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :user
	belongs_to :boat
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	belongs_to :boat

	validates :name, uniqueness: true

	validates :cost, numericality: { greater_than: 1000 }

	validates :description, length: { minimum: 50 }

	validates :origin, inclusion: {in: ["Miami", "Chicago", "Portland", "New York City", "Balitmore", "Boston", "Shanghai", "London", "Amsterdam", "Sydney", "Capetown"]}

	validates :destination, inclusion: {in: ["Miami", "Chicago", "Portland", "New York City", "Balitmore", "Boston", "Shanghai", "London", "Amsterdam", "Sydney", "Capetown"]}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :jobs
	has_many :boats
	has_many :follows
	has_many :vessels, through: :follows, source: :boat
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    if @boat.save
      flash[:notice] = "Welcome to the fleet, #{@boat.name}!"
      redirect_to boat_path(@boat)
    else
      render 'new'
    end
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    flash[:notice] = "Bon voyage, #{@boat.name}!"
    redirect_to boats_path
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    if @boat.update(boat_params)
      redirect_to boat_path(@boat)
    else
      render 'new'
    end
  end

  def show
    current_user
    current_admin
    @boat = Boat.find(params[:id])
    @job = Job.new
    @jobs = Job.where(boat_id: @boat.id)
    if current_user
      @follow = Follow.where(user_id: @current_user.id, boat_id: @boat.id).first
    end
    puts @follow
    @follows = Follow.where(boat_id: @boat.id)
  end

  def index
    @boats = Boat.all
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :location, :email, :capacity, :user_id, :boat_pic)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  def create
  	current_user
  	current_admin
  	@follow = Follow.new(user_id: current_user.id, boat_id: params[:boat_id])

  	respond_to do |format|
  		if @follow.save
  			flash[:notice] = "You followed this boat!"
  			format.html { redirect_to :back, notice: "You followed this boat!"}
  			format.json { render :show, status: :created, location: @follow}
        format.js
        # ^ doesn't seem to be working
  		else
  			format.html { render :new }
  			format.json { render json: @follow.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@follow = Follow.find(params[:id])
  	@boat = Boat.find(params[:id])
  	@follow.destroy
  	respond_to do |format|
  		format.html { redirect_to :back, notice: "You unfollowed this boat! That's cold!"}
  		format.json { head :no_content }
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def show
  	
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @job = Job.new
    # @boat = Boat.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      # @boat = Boat.find(@job.boat_id)
      redirect_to boat_path(@job.boat_id)
    else
      render 'boat_path'
    end
  end

  def destroy
    # @boat = Boat.find(params[:id])
    # @job = Job.where(boat_id: @boat.id)
    # @job.destroy
    # redirect_to boat_path(@boat)
    @job = Job.find(params[:id])
    @boat_id = @job.boat_id
    @job.destroy
    flash[:notice] = "A job well done!"
    redirect_to boat_path(@boat_id)
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    # way to exclude user_id and boat_id above?
    redirect_to boat_path(@job.boat_id)
  end

  def show
  end

  def index
  end

  private

  def job_params
    params.require(:job).permit(:name, :description, :user_id, :boat_id, :origin, :destination, :containers, :cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def destroy
  end

  def edit
  end

  def update
  end

  def show
    current_user
    current_admin
    @user = User.find(params[:id])
    @fave_boats = @user.vessels
    @boats = Boat.where(user_id: @user_id)
  end

  def index
    @users = User.all
  end

  # private

  # def user_params
  #   params.require(:boat).permit(:name, :location, :email, :capacity)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/boats/create.js.erb
$('.follow-button').click(function() {
	$(this).replaceWith( '<div class="unfollow-button"><button type="button" follow_path="@follow" method=":delete" data-remote="true">Unfollow This Boat</button></div>' )
});

$('.unfollow-button').click(function() {
	$(this).replaceWith( '<div class="follow-button"><button type="button" controller="follows" action="create" boat_id="@boat.id" remote="true">Follow This Boat</div>')
});

app/views/boats/edit.html.erb
	Edit Your Boat:
	<br>
	<%= form_for @boat do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<br>
	<%= f.label :capacity %>
	<%= f.number_field :capacity %>
	<% if current_admin %>
		<%= f.hidden_field :user_id, :value => current_admin.id %>
	<% else %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
	<% end %>
	<%= f.submit %>
	<% end %>

app/views/boats/index.html.erb
SO MANY BOATS
<br>
<% if current_user || current_admin %>
	<%= link_to "Create a New Boat", new_boat_path %>
	<br>
<% else %>
<% end %>
<hr>
<br>
<% @boats.each do |boat| %>
<%= image_tag boat.boat_pic.url(:thumb) %>
<%= link_to boat.name, boat_path(boat.id) %>
<br>
<%= boat.location %>
<br>
<%= boat.capacity %>
<hr>
<% end %>
<br>
<%= link_to "Go Home", "/" %>

app/views/boats/new.html.erb
<% if current_user || current_admin %>
	<%= form_for @boat, html: { multipart: true } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<br>
	<!-- ^ change this to f.select/drop-down menu with list of cities? -->
	<%= f.label :capacity %>
	<%= f.number_field :capacity %>
	<br>
	<%= f.label "Photo" %>
	<%= f.file_field :boat_pic %>
	<% if current_admin %>
		<%= f.hidden_field :user_id, :value => current_admin.id %>
	<% else %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
	<% end %>
	<br>
	<%= f.submit "Create My Boat" %>
	<% end %>
	<br>
	<% if @boat.errors.full_messages.any? %>
	  <ul>
	    <% @boat.errors.full_messages.each do |error_message| %>
	      <li><%= error_message%></li> <br />
	    <% end %>
	  </ul>
	<% end %>
<% else %>
<% end %>
<%= link_to "Go Home", '/' %>

app/views/boats/show.html.erb
<!-- boat name & info -->
Boat Name: <%= @boat.name %>
<br>
<%= image_tag @boat.boat_pic.url(:medium) %>
<br>
Location: <%= @boat.location %>
<br>
Capacity: <%= @boat.capacity %>
<br>
<% if @boat.user %>
	Belongs To: <a href="../users/<%= @boat.user_id %>"><%= @boat.user.email %></a>
<% else %>
	This boat has no captain!
<% end %>

<br>

<!-- button to follow/unfollow boat -->
<% if current_user || current_admin %>
	<% if !@follow %>
		<div class="follow-button">
		<%= button_to "Follow This Boat", {controller: "follows", action: "create", boat_id: @boat.id}, remote: true %>
		</div>
	<% else %>
		<div class="unfollow-button">
		<%= button_to "Unfollow This Boat", follow_path(@follow), method: :delete, remote: true %>
		</div>
	<% end %>
<% end %>
<!-- ^ might need to change the button_to parameters to incorporate UJS/AJAX - possibly action is completing (in controller) before js functions can run? -->

<%= @boat.name %> has <%= @follows.count %> follower<% if @follows.count != 1 %>s<% end %>!
<br>

<!-- buttons to edit/delete boat -->
<% if current_user || current_admin %>
	<% if current_admin || @boat.user_id == @current_user.id %>
		<%= link_to "Edit This Boat", edit_boat_path %>
		<br>
		<%= link_to "Delete This Boat", boat_path(@boat), method: :delete %>
	<% end %>
<% end %>

<hr>

<!-- form for new job -->
<% if current_user || current_admin %>
	<% if current_admin || @boat.user_id == @current_user.id %>
		Hire Me:
		<br>
		<%= form_for @job do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<br>
			<%= f.label :description %>
			<%= f.text_field :description %>
			<br>
			<%= f.label :containers %>
			<%= f.number_field :containers %>
			<br>
			<%= f.label :cost %>
			<%= f.number_field :cost, :class => 'text_field', :step => 0.01 %>
			<br>
			<%= f.label :origin %>
			<%= f.text_field :origin %>
			<br>
			<%= f.label :destination %>
			<%= f.text_field :destination %>
			<% if current_admin %>
			<!-- ^ change these two to f.select / drop-down menus with list of cities? -->
				<%= f.hidden_field :user_id, :value => current_admin.id %>
			<% else %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
			<% end %>
			<%= f.hidden_field :boat_id, :value => @boat.id %>
			<%= f.submit %>
			<hr>
		<% end %>
			<% if @job.errors.full_messages.any? %>
			  <ul>
			    <% @job.errors.full_messages.each do |error_message| %>
			      <li><%= error_message%></li> <br />
			    <% end %>
			  </ul>
			<% end %>
	<% end %>
<% end %>

<!-- list of current jobs -->
<% if @jobs.count > 0 %>
	Current Jobs:
	<br>
	<br>
	<% @jobs.each do |job| %>
		Job Name: <%= job.name %>
		<br>
		Cargo Description: <%= job.description %>
		<br>
		Price: $<%= job.cost %>0
		<br>
		Container Count: <%= job.containers %>
		<br>
		Origin: <%= job.origin %>
		<br>
		Destination: <%= job.destination %>
		<br>
		<% if current_user || current_admin %>
			<% if current_admin || @boat.user_id == @current_user.id %>
				<%= link_to "Edit This Job", edit_job_path(job.id) %>
				<br>
				<%= link_to "Delete This Job", job_path(job), method: :delete %>
			<% end %>
		<% end %>
		<hr>
	<% end %>
<% end %>
<br>

<!-- link to go home -->
<%= link_to "Return to the Boat List", boats_path %>
<br>
<%= link_to "Go Home", '/' %>

app/views/captains/index.html.erb
OK CAPTAINS
<hr>
<br>
<% @users.each do |user| %>
<%= user.email %>
<!-- <a href="users/<%= user.id %>"><%= user.email %></a> -->
<!-- <%= link_to user.email, users_path(user) %>  -->
<br>
<% end %>
<br>
<%= link_to "Go Home", "/" %>

app/views/captains/show.html.erb
<% if current_user %>
	<%= @user.email %>
	<br>
	<hr>
	<h2>My Boats:</h2>
	<br>
	<% @boats.each do |boat| %>
	<%= link_to boat.name, boat_path(boat.id) %>
	<br>
	<%= boat.location %>
	<br>
	<%= boat.capacity %>
	<hr>
	<% end %>
	<hr>
<% else %>
<% end %>
<%= link_to "Go Home", '/' %>

app/views/home/index.html.erb
<div id="homebody">

	<h1>OK Captain</h1>
	<nav>
	<ul>

			<% if !current_user && !current_admin %>
				<li><%= link_to "Sign Up or Log In", new_user_registration_path %></li>
				
				<li><%= link_to "Sign Up or Log In (Admin)", new_admin_registration_path %></li>
				
			<% else %>
			<% end %>
			<li><%= link_to "User List", users_path %></li>
			
			<li><%= link_to "Boat List", boats_path %></li>
			
			<% if current_user || current_admin %>
				<li><%= link_to "Create a New Boat", new_boat_path %></li>
			
			<% else %>
			<% end %>
			<% if current_user || current_admin %>
			<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<% else %>
			<% end %>
	</ul>

	</nav>

</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/jobs/edit.html.erb
Edit This Job:
<br>
<%= form_for @job do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<%= f.label :containers %>
<%= f.number_field :containers %>
<br>
<%= f.label :cost %>
<%= f.number_field :cost, :class => 'text_field', :step => 0.01 %>
<br>
<%= f.label :origin %>
<%= f.text_field :origin %>
<br>
<%= f.label :destination %>
<%= f.text_field :destination %>
<%= f.submit %>
<% end %>
<% if @job.errors.full_messages.any? %>
  <ul>
    <% @job.errors.full_messages.each do |error_message| %>
      <li><%= error_message%></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>

app/views/jobs/new.html.erb
Create a New Job:
<br>
<%= form_for @job do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :description %>
<%= f.text_field :description %>
<br>
<%= f.label :containers %>
<%= f.number_field :containers %>
<br>
<%= f.label :cost %>
<%= f.number_field :cost, :class => 'text_field', :step => 0.01 %>
<br>
<%= f.label :origin %>
<%= f.text_field :origin %>
<br>
<%= f.label :destination %>
<%= f.text_field :destination %>
<br>
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.hidden_field :boat_id, :value => @job.boat_id %>
<%= f.submit %>
<% end %>
<% if @job.errors.full_messages.any? %>
  <ul>
    <% @job.errors.full_messages.each do |error_message| %>
      <li><%= error_message%></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OkCaptain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Chicle' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
OK CAPTAINS
<hr>
<br>
<% @users.each do |user| %>
<a href="users/<%= user.id %>"><%= user.email %></a>
<br>
<% end %>
<br>
<%= link_to "Go Home", "/" %>

app/views/users/show.html.erb
<%= @user.email %>
<br>
<hr>
<h2>My Boats:</h2>
<br>
<% @boats.each do |boat| %>
	<%= link_to boat.name, boat_path(boat.id) %>
	<br>
	<%= boat.location %>
	<br>
	<%= boat.capacity %>
	<hr>
<% end %>
	
<h2>Boats I'm Following:</h2>
<% @fave_boats.each do |fave| %>
	Boat Name: <%= link_to fave.name, boat_path(fave.id) %>
	<br>
	<%= image_tag fave.boat_pic.url(:thumb) %>
	<br>
	Location: <%= fave.location %>
	<br>
	Capacity: <%= fave.capacity %>
	<br>
	<% if fave.user %>
		Belongs To: <a href="../users/<%= fave.user_id %>"><%= fave.user.email %></a>
	<% else %>
		This boat has no captain!
	<% end %>
	<br>
	<hr>
<% end %>
<%= link_to "Go Home", '/' %>